name: 'hola mundo'
description: 'escribe un nombre y saluda'

inputs:
  who-to-greet:
    description: 'who to greet'
    required: false
    default: 'mundo'

outputs:
  time:
    description: 'Hora del saludo'

runs:
  using: 'node16' 
  main: 'index.js'